# Generated by Django 4.0.1 on 2022-03-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=50)),
                ('book_text', models.TextField(default='', max_length=2000)),
                ('author_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('rating', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('rank', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=50)),
                ('comment_text', models.TextField(max_length=600)),
                ('date', models.DateTimeField(verbose_name='Date published')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('connect_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
            ],
        ),
    ]
