# Generated by Django 4.0.1 on 2022-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_modern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
