# Generated by Django 4.0.1 on 2022-04-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_book_author_name_alter_book_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_text',
            new_name='book_description',
        ),
    ]
