# Generated by Django 4.0.1 on 2022-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_book_text_book_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
