# Generated by Django 4.0.1 on 2022-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name_review',
            field=models.CharField(default='', max_length=75),
        ),
    ]
