# Generated by Django 4.0.1 on 2022-04-15 17:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_review_name_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
