# Generated by Django 4.0.1 on 2022-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_review_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
