# Generated by Django 4.0.1 on 2022-04-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_review_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='connect_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.book'),
        ),
    ]
