# Generated by Django 4.0.1 on 2022-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
