# Generated by Django 4.0.1 on 2022-05-28 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0014_review_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='liked',
        ),
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
