# Generated by Django 4.0.1 on 2022-09-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='modern',
        ),
    ]
