# Generated by Django 4.0.1 on 2022-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_remove_book_modern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('COMMON', 'Common'), ('MODERN', 'Modern'), ('POPULAR', 'Popular')], default='COMMON', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='modern',
            field=models.BooleanField(default=False),
        ),
    ]
