# Generated by Django 4.0.1 on 2022-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_rename_category_book_type_remove_book_modern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rank',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
